#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter '/afs/cern.ch/work/a/amartell/Linearity/Linearity//data/2012/Winter2013/EoP_stdCat_nonGlobe_powheg-runDependent_phoTunedRegV5_Dphi3p15/jobs//job_cat2.sh'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
