#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter '/afs/cern.ch/work/a/amartell/Linearity/Linearity//data/2011/Winter2013/MZ_stdCat_nonGlobe_7TeV-allRange_7TeVTuned_Dphi3p15/jobs//job_cat1.sh'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
